name: sikomti_app
description: "App for mobile and the title is Compensation System of Information Technology Department of Malang State Polytechnic."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  file_picker: ^5.0.0
  path: ^1.8.0
  percent_indicator: ^4.2.3
  http: ^1.2.2
  shared_preferences: ^2.3.3
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.1
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  dio: ^5.7.0
  open_file: ^3.3.2
  flutter_downloader: ^1.11.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/logo_jti_polinema.png
    - assets/img/profil1.jpg
    - assets/img/SIKOMTI.png
